### ISSUE TITLE
It's misspelled, it should be....

### ISSUE THREAD

**Issue by chenpaner** [Barrunterio/Collection-Selection-Viewer#1]
bpy.utils.register_class(BRT_Collection_Viewer_Selection_PreferencesPanel)
bpy.utils.unregister_class(BRT_Collection_Viewer_Selection_PreferencesPanel)

It's misspelled, it should be

bpy.utils.register_class(TRT_Collection_Viewer_Selection_PreferencesPanel)
bpy.utils.unregister_class(TRT_Collection_Viewer_Selection_PreferencesPanel)

**Comment by Barrunterio** [comment]
Corrected, name changed from TRT_Collection_Viewer_Selection_PreferencesPanel to --> BRT_Collection_Viewer_Selection_PreferencesPanel
